### ISSUE TITLE
playing freeze

### ISSUE THREAD

**Issue by wchuan163** [botbahlul/Live-Subtitle#1]
google speech live subtitle can not smoothly work while playing movies, what is the problem

**Comment by botbahlul** [comment]
I've wrote about that in README

You should use VLC to play the video/audio, then you can use this app to display its SUBTITLES

If you want to watch directly from browser, you can try VOSK LIVE SUBTITLE
https://github.com/botbahlul/VOSK-Powered-Live-Subtitle-V3

It has CONTINUOS FULL DUPLEX SPEECH RECOGNIZER but ONLY SUPPORT 21 LANGUAGES.

Free Google Speech Recognition support 132 languages, but doesn't support full duplex speech recognition.
